name: macOS
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@master
      - name: Install dependencies
        run: |
          brew bundle
      - name: Build
        run: |
          meson ../opencv-glib.build
          ninja -C ../opencv-glib.build
      - name: Install gems for test
        run: |
          bundle install
      - name: Test
        run: |
          cd ../opencv-glib.build
          bundle exec ../opencv-glib/test/run-test.sh
